//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuf.infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CufDBContext : DbContext
    {
        public CufDBContext()
            : base("name=CufDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Constituent> Constituents { get; set; }
        public virtual DbSet<PollingStation> PollingStations { get; set; }
        public virtual DbSet<Shehia> Shehias { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
        public virtual DbSet<Word> Words { get; set; }
        public virtual DbSet<PollingShehia> PollingShehias { get; set; }
    }
}
