//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuf.infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voter
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DateBirth { get; set; }
        public string Gender { get; set; }
        public string ResidentialAddress { get; set; }
        public int PollingStationId { get; set; }
        public int ResidentialConstituencyId { get; set; }
        public int VotingConstituencyId { get; set; }
        public Nullable<int> VoterIDNumber { get; set; }
        public string LifeStatus { get; set; }

        public System.Data.Entity.EntityState State { get; set; }
    }
}
